export const metadata = {
  title: 'MyEasyPharma',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.png" />
      <link href="https://fonts.cdnfonts.com/css/lufga" rel="stylesheet"></link>

      </head>
      <body style={{"overflow":"hidden"}}>{children}</body>
    </html>
  )
}
